version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: parking123
      POSTGRES_DB: parkingdb
    container_name: parking
    volumes:
      - ./postgres:/var/lib/postgresql/data
