# Generated by Django 4.2.16 on 2024-10-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppParking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="direccion",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usuario",
            name="telefono",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
