# Generated by Django 4.2.16 on 2024-11-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppParking", "0003_alter_usuario_parqueadero"),
    ]

    operations = [
        migrations.AddField(
            model_name="propietario",
            name="edad",
            field=models.IntegerField(default=18),
        ),
    ]
